version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for Dockerfile in the `root` directory
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
