name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
    - master
    - version-*
    paths:
    - gradle.properties

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        proto:
          - conn-fix
          - conn-ntg
          - conn-soup
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "::set-output name=REPOSITORY_NAME::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        id: meta
      - name: Read version from gradle.properties
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: ./gradle.properties
          properties: release_version
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            project_name=${{ matrix.proto }}
          push: true
          tags: ghcr.io/th2-net/th2-${{ matrix.proto }}:${{ steps.read_property.outputs.value }}
          labels: com.exactpro.th2.th2-${{ matrix.proto }}=${{ steps.read_property.outputs.value }}
