name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
    - master
    - version-*
    paths:
    - gradle.properties
#    - package_info.json

jobs:
  build:
    strategy:
      matrix:
        proto:
          - conn-fix
          - conn-ntg
          - conn-soup
    uses: th2-net/.github/.github/workflows/matrix-java-docker.yml@th2-4135-matrix-workflow
    with:
      runsOn: ubuntu-20.04
      projectName: ${{ matrix.proto }}
      build-target: 'Docker'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
